[workspace]
members=[
"db",
"resolver",
"db-exporter",
"common",
"wantlist-client",
"ipfs-json-to-csv",
"ipfs-gateway-finder",
"wantlist-client-lib",
"ipfs-walk-tree",
"cid-decode",
"csv-to-graph",
"unify-bitswap-traces",
    "bitswap-db-test"
]